# Docker compose with .NET6, run dotnet publish and run the app
version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d pgdb"]
      interval: 2s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432

  api:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5678:80
    depends_on:
      - db
